name: Terraform CI/CD - CloudScale Project 2

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-build-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v3
        with:
          username: jibreel3932
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: jibreel3932/cloudscale-app:latest

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: docker-build-push
    env:
      ARM_CLIENT_ID:       ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET:   ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID:       ${{ secrets.ARM_TENANT_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: "1.9.0"
      - run: tofu init
      - run: tofu validate
      - run: |
          tofu plan \
            -var="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" \
            -var="client_id=${{ secrets.ARM_CLIENT_ID }}" \
            -var="client_secret=${{ secrets.ARM_CLIENT_SECRET }}" \
            -var="tenant_id=${{ secrets.ARM_TENANT_ID }}" \
            -var="student_name=JibrelAbubakrJibrel" \
            -var="docker_image=jibreel3932/cloudscale-app:latest" \
            -out=tfplan
      - uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan

  approval:
    name: Awaiting Manual Approval
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production
    steps:
      - run: echo "Approved! Proceeding with deployment."

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: approval
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    env:
      ARM_CLIENT_ID:       ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET:   ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID:       ${{ secrets.ARM_TENANT_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: "1.9.0"
      - run: tofu init
      - uses: actions/download-artifact@v3
        with:
          name: tfplan
      - run: |
          tofu apply \
            -var="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" \
            -var="client_id=${{ secrets.ARM_CLIENT_ID }}" \
            -var="client_secret=${{ secrets.ARM_CLIENT_SECRET }}" \
            -var="tenant_id=${{ secrets.ARM_TENANT_ID }}" \
            -var="student_name=JibrelAbubakrJibrel" \
            -var="docker_image=jibreel3932/cloudscale-app:latest" \
            -auto-approve
      - run: tofu output
